# main.py — Build A Student Grade Tracker With Fastapi Add
# Generated by VIA

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
import logging
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting Build A Student Grade Tracker With Fastapi Add...")
    yield
    logger.info("Shutting down...")


app = FastAPI(
    title="Build A Student Grade Tracker With Fastapi Add",
    description="Generated by VIA — Autonomous AI Platform",
    version="1.0.0",
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

from routers import items
app.include_router(items.router, prefix="/api/v1", tags=["Items"])


@app.get("/")
async def root():
    return {
        "app": "Build A Student Grade Tracker With Fastapi Add",
        "status": "running",
        "docs": "/docs",
        "generated_by": "VIA"
    }

@app.get("/health")
async def health():
    return {"status": "ok"}
